# SPDX-FileCopyrightText: 2024 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: MIT

[default]
path = "~/Pictures/Wallpapers"
recursive = false
duration = "10m"
mode = "center"
transition-time = 1000
