# SPDX-FileCopyrightText: 2024 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: MIT

[default]
path = "~/Pictures/Wallpapers/Current"
duration = "10m"
mode = "center"
transition-time = 1000
