# SPDX-FileCopyrightText: 2023 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: MIT

line-length = 79

[lint]
extend-select = ["C90", "D", "I"]

[lint.pydocstyle]
convention = "google"
