version = 1

[[annotations]]
path = "screenshots/**"
SPDX-FileCopyrightText = "2023 Harish Rajagopal <harish.rajagopals@gmail.com>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "fish/.config/fish/fish_plugins"
SPDX-FileCopyrightText = "2023 Harish Rajagopal <harish.rajagopals@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "kvantum/.config/Kvantum/**.kvconfig"
SPDX-FileCopyrightText = "2024 Harish Rajagopal <harish.rajagopals@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"
