; SPDX-FileCopyrightText: 2026 Harish Rajagopal <harish.rajagopals@gmail.com>
;
; SPDX-License-Identifier: MIT
[General]
autoCloseIdleDaemon=true
contrastOpacity=188
disabledTrayIcon=true
saveAsFileExtension=png
savePath=/home/rharish/Pictures/Screenshots
