# SPDX-FileCopyrightText: 2020 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: MIT

# LuaLaTeX support
$pdf_mode = 4;

# Specify more extensions to remove when cleaning
$clean_ext = "nav snm"; # for -c
$clean_full_ext = "bbl" # for -C
