# SPDX-FileCopyrightText: 2023 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: MIT

format = """
[](white)\
$os\
[](bg:blue fg:white)\
$directory\
[](fg:blue bg:green)\
$git_branch\
$git_status\
[](green)\
$fill\
[](yellow)\
$cmd_duration\
[](fg:cyan bg:yellow)\
$c\
$golang\
$gradle\
$haskell\
$java\
$nodejs\
$python\
$rust\
[](cyan)
$character
"""

[os]
style = "fg:black bg:white"
disabled = false # Disabled by default

[os.symbols]
Arch = " "

[directory]
style = "fg:black bg:blue"
format = "[ $path ]($style)"
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:black bg:green"
format = '[ $symbol $branch]($style)'

[git_status]
style = "fg:black bg:green"
format = '[ $all_status$ahead_behind ]($style)'

[fill]
symbol = "─"
style = "#555555"

[c]
symbol = " "
style = "fg:black bg:cyan"
format = '[ $symbol($version) ]($style)'

[golang]
symbol = " "
style = "fg:black bg:cyan"
format = '[ $symbol($version) ]($style)'

[gradle]
style = "fg:black bg:cyan"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:black bg:cyan"
format = '[ $symbol($version) ]($style)'

[java]
symbol = " "
style = "fg:black bg:cyan"
format = '[ $symbol($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:black bg:cyan"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "fg:black bg:cyan"
format = '[ $symbol($version) ]($style)'
pyenv_version_name = true

[rust]
symbol = ""
style = "fg:black bg:cyan"
format = '[ $symbol ($version) ]($style)'

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:black bg:yellow"
