# SPDX-FileCopyrightText: 2022 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: MIT

monitor=,preferred,0x0,1
workspace=DP-1,1

input {
    sensitivity=0.2 # for mouse cursor
    follow_mouse=2 # focus mouse on other windows on hover but not the keyboard
    float_switch_override_focus=false
    kb_options=compose:menu # use the menu button as the compose key
    numlock_by_default=true # enable numlock by default
    touchpad {
        natural_scroll=true
    }
}

general {
    apply_sens_to_raw=false # whether to apply the sensitivity to raw input (e.g. used by games where you aim using your mouse)

    gaps_in=5
    gaps_out=10
    border_size=0
    col.group_border_active=0xffcccccc
    col.group_border=0xff515151
}

decoration {
    rounding=5

    blur=false
    dim_inactive=true
    dim_strength=0.3

    drop_shadow=true
    shadow_range=15
}

animations {
    enabled=1
    animation=windows,1,7,default
    animation=border,1,10,default
    animation=fade,1,10,default
    animation=workspaces,1,6,default
}

dwindle {
    preserve_split=1 # Allow toggling manual split direction
}

gestures {
    workspace_swipe=true
}

misc {
    disable_hyprland_logo=true
}

# Window rules
windowrule=float,lollypop
windowrule=float,zoom
windowrule=float,Matplotlib
windowrule=move 10 50,xfce4-notifyd
windowrule=float,title:Password Required - Mozilla Thunderbird

# Startup scripts
source=~/.config/hypr/startup.conf

# Keybinds
source=~/.config/hypr/keybinds.conf
