# SPDX-FileCopyrightText: 2022 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: MIT

exec-once = aa-notify -p -s 1 -w 60 -f /var/log/audit/audit.log # AppArmor notifications on denials
exec-once = corectrl --minimize-systray
exec-once = gammastep-indicator
exec-once = kdeconnectd
exec-once = kdeconnect-indicator
exec-once = system-config-printer-applet # Printer status
exec-once = systemctl --user start hyprpolkitagent # GUI auth via Polkit
exec-once = systemctl --user start xfce4-notifyd.service
exec-once = hyprctl setcursor Breeze_Light 24 # Set the cursor theme.
exec-once = Thunar --daemon
exec-once = cursor-clip --daemon # Clipboard manager
exec-once = ashell # Status bar + tray
exec-once = hypridle # Power management for Hyprland
exec-once = hyprpm reload # Enable Hyprland plugins.
exec-once = wpaperd -d # Wallpaper daemon for random wallpapers
