# SPDX-FileCopyrightText: 2022 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: MIT

# ----------------------------------------
# Status bar and tray
# ----------------------------------------

# Start Waybar
exec-once=waybar

# Manage network connections
exec-once=nm-applet --indicator

# Blueman Bluetooth Manager
exec-once=blueman-applet

# KDE Connect daemon
exec-once=kdeconnect-indicator

# System tray icon for managing print jobs
exec-once=system-config-printer-applet

# TODO: Custom rclonesync indicator using yad
# exec-once=~/Programs/Shell/rclone-yad.zsh

# Color temperature adjustment tool
exec-once=gammastep-indicator -m wayland

# PolyBox file synchronization
exec-once=owncloud

# ----------------------------------------
# Daemons
# ----------------------------------------

# A tool for managing global GTK recently-used files list
exec-once=gtk-recent-scrubber

# Receive on screen notifications of AppArmor denials
exec-once=aa-notify -p -s 1 -w 60 -f /var/log/audit/audit.log

# Schedules backups at regular intervals
exec-once=/usr/lib/deja-dup/deja-dup-monitor

# Run thunar as daemon
exec-once=thunar --daemon

# PolicyKit Authentication Agent
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Xfce Notification Daemon
exec-once=/usr/lib/xfce4/notifyd/xfce4-notifyd

# ----------------------------------------
# One-time services
# ----------------------------------------

# Set the wallpaper
exec-once=~/Programs/Shell/swaybg-rand.fish

# Set the cursor theme
exec-once=hyprctl setcursor Breeze_Snow 24

# ----------------------------------------
# Portal setup
# ----------------------------------------

exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
